# Generated by Django 5.2.17 on 2026-09-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255, unique=True, verbose_name='внешний идентификатор')),
                ('user_id', models.BigIntegerField(verbose_name='идентификатор пользователя')),
                ('email', models.EmailField(max_length=254, verbose_name='email получателя')),
                ('subject', models.CharField(max_length=255, verbose_name='тема письма')),
                ('message', models.TextField(verbose_name='текст письма')),
                ('status', models.CharField(choices=[('pending', 'Ожидает отправки'), ('sent', 'Отправлено'), ('failed', 'Ошибка отправки')], db_index=True, default='pending', max_length=16, verbose_name='статус')),
                ('last_error', models.TextField(blank=True, verbose_name='последняя ошибка отправки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='отправлено')),
            ],
            options={
                'verbose_name': 'письмо',
                'verbose_name_plural': 'письма',
                'ordering': ('pk',),
            },
        ),
    ]
